# INSTRUCTIONS:
# - ONLY EDIT THE PASSWORD BELOW.
# - DO NOT EDIT ANY OTHER PART OF THIS FILE.

# BEGIN EDITABLE SECTION
password = "remarkable_password" # ie: 9VtYkl7r7D
# END EDITABLE SECTION

# DO NOT EDIT BELOW THIS LINE
hostname = "10.11.99.1"
username = "root"

